import type { AudioManifest } from './audioTypes'

export const audioManifest = {
  contador_5: {
    id: 'contador_5',
    path: '/audio/voz/contador_5.mp3',
    category: 'voice',
    defaultVolume: 0.92,
    loop: false,
    preload: true,
    required: true,
    description: 'Voz do contador: cinco.',
  },
  contador_4: {
    id: 'contador_4',
    path: '/audio/voz/contador_4.mp3',
    category: 'voice',
    defaultVolume: 0.92,
    loop: false,
    preload: true,
    required: true,
    description: 'Voz do contador: quatro.',
  },
  contador_3: {
    id: 'contador_3',
    path: '/audio/voz/contador_3.mp3',
    category: 'voice',
    defaultVolume: 0.92,
    loop: false,
    preload: true,
    required: true,
    description: 'Voz do contador: tres.',
  },
  contador_2: {
    id: 'contador_2',
    path: '/audio/voz/contador_2.mp3',
    category: 'voice',
    defaultVolume: 0.92,
    loop: false,
    preload: true,
    required: true,
    description: 'Voz do contador: dois.',
  },
  contador_1: {
    id: 'contador_1',
    path: '/audio/voz/contador_1.mp3',
    category: 'voice',
    defaultVolume: 0.92,
    loop: false,
    preload: true,
    required: true,
    description: 'Voz do contador: um.',
  },
  contador_0_valendo: {
    id: 'contador_0_valendo',
    path: '/audio/voz/contador_0_valendo.mp3',
    category: 'voice',
    defaultVolume: 0.96,
    loop: false,
    preload: true,
    required: true,
    description: 'Voz do contador: valendo.',
  },
  tempo_resposta_relogio_tenso: {
    id: 'tempo_resposta_relogio_tenso',
    path: '/audio/sfx/tempo_resposta_relogio_tenso.mp3',
    category: 'sfx',
    defaultVolume: 0.42,
    loop: true,
    preload: true,
    required: true,
    description: 'Loop leve de relogio tenso durante a janela de resposta.',
  },
  grupo_pegou_vez: {
    id: 'grupo_pegou_vez',
    path: '/audio/Buzzer sound effect - Sound Meme (youtube).mp3',
    category: 'sfx',
    defaultVolume: 0.72,
    loop: false,
    preload: true,
    required: true,
    description: 'Impacto curto quando um grupo pega a vez.',
  },
  resposta_certa: {
    id: 'resposta_certa',
    path: '/audio/sfx/resposta_certa.mp3',
    category: 'sfx',
    defaultVolume: 0.76,
    loop: false,
    preload: true,
    required: true,
    description: 'Feedback curto de resposta correta.',
  },
  resposta_errada: {
    id: 'resposta_errada',
    path: '/audio/sfx/resposta_errada.mp3',
    category: 'sfx',
    defaultVolume: 0.72,
    loop: false,
    preload: true,
    required: true,
    description: 'Feedback curto de resposta errada.',
  },
  tempo_esgotado: {
    id: 'tempo_esgotado',
    path: '/audio/sfx/tempo_esgotado.mp3',
    category: 'sfx',
    defaultVolume: 0.78,
    loop: false,
    preload: true,
    required: true,
    description: 'Fechamento curto para tempo esgotado.',
  },
  veredito_final: {
    id: 'veredito_final',
    path: '/audio/stingers/veredito_final.mp3',
    category: 'stinger',
    defaultVolume: 0.82,
    loop: false,
    preload: true,
    required: true,
    description: 'Stinger de entrada do Veredito Final.',
  },
  fim_de_jogo: {
    id: 'fim_de_jogo',
    path: '/audio/stingers/fim_de_jogo.mp3',
    category: 'stinger',
    defaultVolume: 0.84,
    loop: false,
    preload: true,
    required: true,
    description: 'Stinger de encerramento do jogo.',
  },
  preshow_theme: {
    id: 'preshow_theme',
    path: '/audio/Batman Theme (from Batman A Greenway Production in association with Twentieth Century-Fox... - Neal Hefti & his Orchestra and Chorus (youtube).mp3',
    category: 'music',
    defaultVolume: 0.24,
    loop: true,
    preload: false,
    required: false,
    description: 'Trilha local fornecida pelo usuario para o pre-show. Uso local pendente de confirmacao de direitos.',
  },
  desafio_tribunal_theme: {
    id: 'desafio_tribunal_theme',
    path: '/audio/music/desafio_tribunal_theme.mp3',
    category: 'music',
    defaultVolume: 0.38,
    loop: true,
    preload: false,
    required: false,
    description: 'Trilha leve derivada do arquivo local fundo tribunal para o Desafio do Tribunal.',
  },
} satisfies AudioManifest
